controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
product_index:
    path: client/produits
    controller: App\Controller\ProduitsController::index